/**
 *
 *  EventsTagsController.cc
 *  This file is generated by drogon_ctl
 *
 */

#include "EventsTagsController.h"
#include <string>



void EventsTagsController::get(const HttpRequestPtr &req,
                               std::function<void(const HttpResponsePtr &)> &&callback)
{
    EventsTagsControllerBase::get(req, std::move(callback));
}

void EventsTagsController::create(const HttpRequestPtr &req,
                                  std::function<void(const HttpResponsePtr &)> &&callback)
{
    EventsTagsControllerBase::create(req, std::move(callback));
}
