/**
 *
 *  EventsTagsController.h
 *  This file is generated by drogon_ctl
 *
 */

#pragma once

#include <drogon/HttpController.h>
#include "EventsTagsControllerBase.h"

#include "EventsTags.h"
using namespace drogon;
using namespace drogon_model::augventure_db;
/**
 * @brief this class is created by the drogon_ctl command.
 * this class is a restful API controller for reading and writing the events_tags table.
 */

class EventsTagsController: public drogon::HttpController<EventsTagsController>, public EventsTagsControllerBase
{
  public:
    METHOD_LIST_BEGIN
    ADD_METHOD_TO(EventsTagsController::get,"/api/eventstags",Get,Options,"augventure::filters::LoginFilter");
    ADD_METHOD_TO(EventsTagsController::create,"/api/eventstags",Post,Options,"augventure::filters::LoginFilter");
    //ADD_METHOD_TO(EventsTagsController::update,"/api/eventstags",Put,Options,"augventure::filters::LoginFilter");
    METHOD_LIST_END
     
    void get(const HttpRequestPtr &req,
             std::function<void(const HttpResponsePtr &)> &&callback);
    void create(const HttpRequestPtr &req,
             std::function<void(const HttpResponsePtr &)> &&callback);

};
