/**
 *
 *  SuggestionsController.cc
 *  This file is generated by drogon_ctl
 *
 */

#include "SuggestionsController.h"
#include <string>


void SuggestionsController::getOne(const HttpRequestPtr &req,
                                   std::function<void(const HttpResponsePtr &)> &&callback,
                                   Suggestions::PrimaryKeyType &&id)
{
    SuggestionsControllerBase::getOne(req, std::move(callback), std::move(id));
}


void SuggestionsController::updateOne(const HttpRequestPtr &req,
                                      std::function<void(const HttpResponsePtr &)> &&callback,
                                      Suggestions::PrimaryKeyType &&id)
{
    SuggestionsControllerBase::updateOne(req, std::move(callback), std::move(id));
}


void SuggestionsController::deleteOne(const HttpRequestPtr &req,
                                      std::function<void(const HttpResponsePtr &)> &&callback,
                                      Suggestions::PrimaryKeyType &&id)
{
    SuggestionsControllerBase::deleteOne(req, std::move(callback), std::move(id));
}

void SuggestionsController::get(const HttpRequestPtr &req,
                                std::function<void(const HttpResponsePtr &)> &&callback)
{
    SuggestionsControllerBase::get(req, std::move(callback));
}

void SuggestionsController::create(const HttpRequestPtr &req,
                                   std::function<void(const HttpResponsePtr &)> &&callback)
{
    SuggestionsControllerBase::create(req, std::move(callback));
}
