services:
  backend:
    container_name: augventure-backend
    build: backend
    ports:
      - "80:80"
    depends_on: 
      db:
        condition: service_healthy
  db:
    container_name: augventure-db
    image: mariadb:latest
    environment:
      MARIADB_ROOT_PASSWORD: 1
      MARIADB_USER: augventureUser
      MARIADB_PASSWORD: augventureUserPassword
      MARIADB_DATABASE: augventure_db
    volumes:
      - ./db_init/create_tables.sql:/docker-entrypoint-initdb.d/create_tables.sql
    healthcheck:
      test: [ "CMD", "healthcheck.sh", "--connect", "--innodb_initialized" ]
      start_period: 1m 
      start_interval: 10s
      interval: 10s # prod 1m
      timeout: 5s
      retries: 3
  frontend:
    container_name: augventure-frontend
    build: frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend


